### ISSUE TITLE
Scripts or symlinks for backward compatibility

### ISSUE THREAD

**Issue by tcatm** [tcatm/ecdsautils#21]
We should add scripts or symlinks offering the same functionality.

**Comment by apfohl** [comment]
I think, you should release one version with the symlinked scripts, which display a deprecation warning. The next step would be, to remove the old behavior. Otherwise you will stick with the old tools forever.

**Comment by tcatm** [comment]
It may even suffice to put compat scripts into a `compat/` subfolder and not package them at all. The release notes could make it very clear that the syntax has changed.

**Comment by apfohl** [comment]
Right.

**Comment by NeoRaider** [comment]
This can be closed.
